# RSS feeds to monitor
feeds:
  1: http://osom.cfa.vic.gov.au/public/osom/IN_COMING.rss

# patterns for which to search in RSS feeds (case-insensitively)
patterns:
  1: upwey
  2: belgrave
  3: olinda

# action to take upon a new pattern match

# MS Windows
#action: "start sounds\\alarm.wav"   

# Linux
#action: "mplayer -quiet -really-quiet sounds/alarm.wav"

# iPhone
#action: "play sounds/alarm.wav"
