# RSS feeds to monitor
feeds:
  1: http://osom.cfa.vic.gov.au/public/osom/IN_COMING.rss
  2: http://osom.cfa.vic.gov.au/public/osom/websites.rss
  
# patterns for which to search in RSS feeds (case-insensitively)
patterns:
  1: upwey
  2: belgrave
  3: tecoma
  4: lysterfield
  5: ferntree
  6: emerald
  7: cockatoo
  8: tremont
  9: selby
  10: sherbrooke
  11: kallista
  12: ferny
  13: basin
  14: dandenong
  15: silvan
  16: monbulk
  17: clematis
  18: evelyn
  19: kalorama
  20: olinda
  21: glenfern
  22: doongalla
  23: sassafras

# action to take upon a new pattern match

# MS Windows
#action: "start sounds\\alarm.wav"   

# Linux
action: "mplayer -quiet -really-quiet sounds/alarm.wav"

# iPhone
#action: "play sounds/alarm.wav"
